{"uuid": "c8a2d182-92be-45aa-825c-a3320e78e209", "children": ["847d3f3e-1d15-481a-8044-9dba342ebc52", "a00dc270-b81b-4cc9-8fef-684f822e9003", "0f455b00-2960-4551-bced-3ff4af87f473", "52469bce-9504-4f85-811b-35b4225d6738"], "befores": [{"name": "setUp", "status": "passed", "start": 1734424637442, "stop": 1734424655233}], "afters": [{"name": "setUp::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: chrome=131.0.6778.140)\nStacktrace:\n\tGetHandleVerifier [0x00007FF71B5B6CC5+28821]\n\t(No symbol) [0x00007FF71B523850]\n\t(No symbol) [0x00007FF71B3C578A]\n\t(No symbol) [0x00007FF71B3B0866]\n\t(No symbol) [0x00007FF71B3B1D1F]\n\t(No symbol) [0x00007FF71B3C5DD3]\n\t(No symbol) [0x00007FF71B39EFCD]\n\t(No symbol) [0x00007FF71B44D699]\n\t(No symbol) [0x00007FF71B43F2C0]\n\t(No symbol) [0x00007FF71B40A778]\n\t(No symbol) [0x00007FF71B40B8E1]\n\tGetHandleVerifier [0x00007FF71B8EFCCD+3408029]\n\tGetHandleVerifier [0x00007FF71B90743F+3504143]\n\tGetHandleVerifier [0x00007FF71B8FB61D+3455469]\n\tGetHandleVerifier [0x00007FF71B67BDCB+835995]\n\t(No symbol) [0x00007FF71B52EB6F]\n\t(No symbol) [0x00007FF71B52A824]\n\t(No symbol) [0x00007FF71B52A9BD]\n\t(No symbol) [0x00007FF71B51A1A9]\n\tBaseThreadInitThunk [0x00007FFA54877374+20]\n\tRtlUserThreadStart [0x00007FFA5509CC91+33]\n\n", "trace": "  File \"C:\\Program Files\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"D:\\Work Data\\Python Automation\\Code file\\GCDemoWebshop_Submit-01\\testcases\\conftest.py\", line 31, in setUp\n    driver.close()\n    ~~~~~~~~~~~~^^\n  File \"C:\\Program Files\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 495, in close\n    self.execute(Command.CLOSE)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Program Files\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1734424664018, "stop": 1734424664028}], "start": 1734424637442, "stop": 1734424664028}